CREATE TABLE `ds_brand` (
                            `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
                            `brand_code` varchar(100) DEFAULT NULL COMMENT '品牌代码',
                            `brand_name` varchar(100) DEFAULT NULL COMMENT '品牌名称',
                            `brand_logo` varchar(80) NOT NULL DEFAULT '' COMMENT '品牌logo图片地址',
                            `brand_desc` text NOT NULL COMMENT '品牌描述',
                            `sort` int(11) DEFAULT NULL COMMENT '排序',
                            `status` tinyint(4) DEFAULT NULL COMMENT '状态  0：停用   1：正常',
                            `version` int(11) DEFAULT NULL COMMENT '版本号',
                            `deleted` tinyint(4) DEFAULT NULL COMMENT '删除标识  0：正常   1：已删除',
                            `creator` bigint(20) DEFAULT NULL COMMENT '创建者',
                            `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                            `updater` bigint(20) DEFAULT NULL COMMENT '更新者',
                            `update_time` datetime DEFAULT NULL COMMENT '更新时间',
                            PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='品牌表';
CREATE TABLE `ds_category` (
                               `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
                               `category_code` varchar(100) DEFAULT NULL COMMENT '品类代码',
                               `category_name` varchar(100) DEFAULT NULL COMMENT '品类名称',
                               `category_desc` text NOT NULL COMMENT '品类描述',
                               `p_id` int(11) NOT NULL DEFAULT '0' COMMENT '父品类ID',
                               `p_code` varchar(20) DEFAULT '' COMMENT '父品类CODE',
                               `sort` int(11) DEFAULT NULL COMMENT '排序',
                               `status` tinyint(4) DEFAULT NULL COMMENT '状态  0：停用   1：正常',
                               `version` int(11) DEFAULT NULL COMMENT '版本号',
                               `deleted` tinyint(4) DEFAULT NULL COMMENT '删除标识  0：正常   1：已删除',
                               `creator` bigint(20) DEFAULT NULL COMMENT '创建者',
                               `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                               `updater` bigint(20) DEFAULT NULL COMMENT '更新者',
                               `update_time` datetime DEFAULT NULL COMMENT '更新时间',
                               PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='品类表';
CREATE TABLE `ds_season` (
                             `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
                             `season_code` varchar(100) DEFAULT NULL COMMENT '季节代码',
                             `season_name` varchar(100) DEFAULT NULL COMMENT '季节名称',
                             `season_desc` text NOT NULL COMMENT '季节描述',
                             `sort` int(11) DEFAULT NULL COMMENT '排序',
                             `status` tinyint(4) DEFAULT NULL COMMENT '状态  0：停用   1：正常',
                             `version` int(11) DEFAULT NULL COMMENT '版本号',
                             `deleted` tinyint(4) DEFAULT NULL COMMENT '删除标识  0：正常   1：已删除',
                             `creator` bigint(20) DEFAULT NULL COMMENT '创建者',
                             `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                             `updater` bigint(20) DEFAULT NULL COMMENT '更新者',
                             `update_time` datetime DEFAULT NULL COMMENT '更新时间',
                             PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='季节表';
CREATE TABLE `ds_series` (
                             `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
                             `series_code` varchar(100) DEFAULT NULL COMMENT '系列代码',
                             `series_name` varchar(100) DEFAULT NULL COMMENT '系列名称',
                             `series_desc` text NOT NULL COMMENT '系列描述',
                             `sort` int(11) DEFAULT NULL COMMENT '排序',
                             `status` tinyint(4) DEFAULT NULL COMMENT '状态  0：停用   1：正常',
                             `version` int(11) DEFAULT NULL COMMENT '版本号',
                             `deleted` tinyint(4) DEFAULT NULL COMMENT '删除标识  0：正常   1：已删除',
                             `creator` bigint(20) DEFAULT NULL COMMENT '创建者',
                             `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                             `updater` bigint(20) DEFAULT NULL COMMENT '更新者',
                             `update_time` datetime DEFAULT NULL COMMENT '更新时间',
                             PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系列表';
CREATE TABLE `ds_year` (
                           `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
                           `year_code` varchar(100) DEFAULT NULL COMMENT '年份代码',
                           `year_name` varchar(100) DEFAULT NULL COMMENT '年份名称',
                           `year_desc` text NOT NULL COMMENT '年份描述',
                           `sort` int(11) DEFAULT NULL COMMENT '排序',
                           `status` tinyint(4) DEFAULT NULL COMMENT '状态  0：停用   1：正常',
                           `version` int(11) DEFAULT NULL COMMENT '版本号',
                           `deleted` tinyint(4) DEFAULT NULL COMMENT '删除标识  0：正常   1：已删除',
                           `creator` bigint(20) DEFAULT NULL COMMENT '创建者',
                           `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                           `updater` bigint(20) DEFAULT NULL COMMENT '更新者',
                           `update_time` datetime DEFAULT NULL COMMENT '更新时间',
                           PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='年份表';
CREATE TABLE `ds_waverange` (
                                `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
                                `waverange_code` varchar(100) DEFAULT NULL COMMENT '波段代码',
                                `waverange_name` varchar(100) DEFAULT NULL COMMENT '波段名称',
                                `waverange_desc` text NOT NULL COMMENT '波段描述',
                                `sort` int(11) DEFAULT NULL COMMENT '排序',
                                `status` tinyint(4) DEFAULT NULL COMMENT '状态  0：停用   1：正常',
                                `version` int(11) DEFAULT NULL COMMENT '版本号',
                                `deleted` tinyint(4) DEFAULT NULL COMMENT '删除标识  0：正常   1：已删除',
                                `creator` bigint(20) DEFAULT NULL COMMENT '创建者',
                                `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                                `updater` bigint(20) DEFAULT NULL COMMENT '更新者',
                                `update_time` datetime DEFAULT NULL COMMENT '更新时间',
                                PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='波段表';
CREATE TABLE `ds_design` (
                             `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
                             `status` tinyint(1) DEFAULT NULL COMMENT '启用状态（1-启用；0-停用）',
                             `brand_id` bigint(20) DEFAULT NULL COMMENT '品牌ID（当前数据所属的品牌，对应SYS_Organization.OrganizationId）',
                             `brand_name` varchar(50) DEFAULT NULL COMMENT '品牌（品牌代码，对应SYS_Organization.OrganizationCode）',
                             `design_code` varchar(50) DEFAULT NULL COMMENT '设计款号',
                             `design_year` int(11) NOT NULL COMMENT '年份',
                             `season_id` bigint(20) DEFAULT NULL COMMENT '季节（春/夏/秋/冬）',
                             `season_name` varchar(50) DEFAULT NULL COMMENT '季节（春/夏/秋/冬）',
                             `waverange_name` varchar(50) DEFAULT NULL COMMENT '波段（标识代码：CPBD，保存名称）',
                             `waverange_id` bigint(20) DEFAULT NULL COMMENT '波段档案Id（对应DS_BandData.Id）',
                             `designer` varchar(50) DEFAULT NULL COMMENT '设计师（设计师角色的账号）',
                             `designer_group_id` bigint(20) DEFAULT NULL COMMENT '设计师所属组别ID',
                             `design_date` datetime DEFAULT NULL COMMENT '设计稿日期',
                             `plan_new_date` date DEFAULT NULL COMMENT '计划上新月份（到月份，默认为1号）',
                             `platform` varchar(50) DEFAULT NULL COMMENT '平台（标识代码：CPPT）',
                             `positioning` varchar(50) DEFAULT NULL COMMENT '产品定位（标识代码：CPDW）',
                             `SELevel` varchar(50) DEFAULT NULL COMMENT '级别（标识代码：CPJB）',
                             `category_id` bigint(20) DEFAULT NULL COMMENT '品类（对应品类标准ds_category）',
                             `sec_oper_category` varchar(100) DEFAULT NULL COMMENT '二次加工（标识代码：ECJGLX）',
                             `from_process_cost` varchar(100) DEFAULT NULL COMMENT '二次工艺（来源二次工艺成本的加工类别，只取费用类别为二次加工，多个英文时逗号间隔）',
                             `style_desc` varchar(200) DEFAULT NULL COMMENT '款式描述',
                             `selling_point` varchar(200) DEFAULT NULL COMMENT '卖点提炼',
                             `merchandiser` varchar(50) DEFAULT NULL COMMENT '跟单员（设计跟单员角色的账号）',
                             `size_group_id` bigint(20) DEFAULT NULL COMMENT '建议尺码组合（多选，标识代码：DHCMZH）',
                             `remark` text COMMENT '备注',
                             `process_category` varchar(50) DEFAULT NULL COMMENT '加工类别（标识代码：JGLB）',
                             `dev_category` varchar(50) DEFAULT NULL COMMENT '研发类别（标识代码：YFLB）',
                             `product_style` varchar(50) DEFAULT NULL COMMENT '产品风格(标识代码CPFG)',
                             `theme` varchar(50) DEFAULT NULL COMMENT '主题',
                             `series_id` bigint(20) DEFAULT NULL COMMENT '系列（标识代码：XLDA）',
                             `version` int(11) DEFAULT NULL COMMENT '版本号',
                             `deleted` tinyint(4) DEFAULT NULL COMMENT '删除标识  0：正常   1：已删除',
                             `creator` bigint(20) DEFAULT NULL COMMENT '创建者',
                             `create_time` datetime DEFAULT NULL COMMENT '创建时间',
                             `updater` bigint(20) DEFAULT NULL COMMENT '更新者',
                             `update_time` datetime DEFAULT NULL COMMENT '更新时间',
                             PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设计款式表';